### ISSUE TITLE
Dibujos

### ISSUE THREAD

**Issue by tomasfiestas** [pdepjm/2023-tp0-presentacion-JoshuaMorales99#1]
Tremendos dibujos, aprendiste a dibujar asi de bien solo o como fue tu camino?

**Comment by JoshuaMorales99** [comment]
Buenas Tomas! 👋🏻 Fui aprendiendo solo, de forma autodidacta.

**Comment by JuniorRodriguez23** [comment]
Muy buenos Dibujos 👍🏾
